---
- name: Deploy onlinebookstore application to Tomcat
  hosts: onlinebookstore
  become: true
  tasks:
    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: /opt/onlinebookstore/target/onlinebookstore-1.0.0.war
        dest: /var/lib/tomcat9/webapps/onlinebookstore.war

    - name: Restart Tomcat service
      service:
        name: tomcat9
        state: restarted
