---
- hosts: onlinebookstore
  become: true
  vars:
    tomcat_user: "{{ ansible_env.USER }}"
    app_path: "/var/lib/tomcat/webapps/onlinebookstore"
    jar_file: "target/onlinebookstore-1.0.0.jar"
    webapp_runner: "target/dependency/webapp-runner.jar"
  tasks:
    - name: Create webapps directory
      file:
        path: "{{ app_path }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        mode: '0755'

    - name: Copy JAR file to Tomcat webapps directory
      copy:
        src: "{{ jar_file }}"
        dest: "{{ app_path }}/"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        mode: '0644'

    - name: Copy webapp-runner JAR to Tomcat lib directory
      copy:
        src: "{{ webapp_runner }}"
        dest: "/usr


    
