---
- name: Deploy onlinebookstore application to Tomcat
  hosts: tomcat
  become: true
  tasks:
    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: /home/jenkins/jenkins_root/workspace/bookstore/target/dependency/webapp-runner.jar
        dest: /var/lib/tomcat9/webapps/ROOT.war
      notify: Restart Tomcat service
      mode: '0755'

    - name: Ensure Tomcat manager app is installed
      apt:
        name: tomcat9-admin
        state: present

    - name: Add manager role to Tomcat users
      lineinfile:
        dest: /etc/tomcat9/tomcat-users.xml
        regexp: '.*<user username="admin" password=".+" roles="manager-gui"/>'
        line: '<user username="admin" password="admin" roles="manager-gui, manager-script"/>'

    - name: Restart Tomcat service
      service:
        name: tomcat9
        state: restarted

  handlers:
    - name: Restart Tomcat service
      service:
        name: tomcat9
        state: restarted





