
---
- hosts: onlinebookstore
  become: true
  tasks:
    - name: Create webapps directory for Tomcat
      become: true
      file:
        path: "/opt/tomcat/webapps"
        state: directory
        mode: '0755'

    - name: Copy JAR file to Tomcat webapps directory
      become: true
      copy:
        src: "target/onlinebookstore-1.0.0.jar"
        dest: "/opt/tomcat/webapps/onlinebookstore.jar"
        mode: '0644'

    - name: Copy webapp-runner JAR to Tomcat lib directory
      become: true
      copy:
        src: "target/dependency/webapp-runner.jar"
        dest: "/opt/tomcat/lib/webapp-runner.jar"
        mode: '0644'

    - name: Stop Tomcat service
      become: true
      service:
        name: "tomcat"
        state: stopped

    - name: Start Tomcat service
      become: true
      service:
        name: "tomcat"
        state: started

