---
- name: Deploy onlinebookstore application to Tomcat
  hosts: your_server_hostname
  become: true
  tasks:
    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: /home/jenkins/jenkins_root/workspace/bookstore/target/dependency/webapp-runner.jar
        dest: /var/lib/tomcat9/webapps/ROOT.war

    - name: Restart Tomcat service
      service:
        name: tomcat9
        state: restarted

    - name: Configure Tomcat Manager
      lineinfile:
        path: /etc/tomcat9/tomcat-users.xml
        regexp: "<\/tomcat-users>"
        line: |
          <role rolename="manager-gui"/>
          <role rolename="manager-script"/>
          <user username="admin" password="admin" roles="manager-gui,manager-script"/>

    - name: Configure Tomcat Host Manager
      lineinfile:
        path: /etc/tomcat9/tomcat-users.xml
        regexp: "<\/tomcat-users>"
        line: |
          <role rolename="admin-gui"/>
          <role rolename="admin-script"/>
          <user username="admin" password="admin" roles="admin-gui,admin-script"/>


