---
- name: Deploy onlinebookstore application to Tomcat
  hosts: webserver
  become: true
  tasks:
    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: /home/jenkins/jenkins_root/workspace/bookstore/target/dependency/webapp-runner.jar
        dest: /var/lib/tomcat9/webapps/onlinebookstore.war

    - name: Restart Tomcat service
      service:
        name: tomcat9
        state: restarted

